spring:
  application:
    name: storefront
  datasource:
    url: jdbc:postgresql://localhost:5432/storefront
    username: rabbitlab
    password: rabbitlab
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitlab
    password: rabbitlab

server:
  port: 8082
